#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : todoist
Version  : 7.0.16
Release  : 6
URL      : https://github.com/Doist/todoist-python/archive/7.0.16.tar.gz
Source0  : https://github.com/Doist/todoist-python/archive/7.0.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: todoist-license = %{version}-%{release}
Requires: todoist-python = %{version}-%{release}
Requires: todoist-python3 = %{version}-%{release}
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : requests
BuildRequires : tox
BuildRequires : virtualenv

%description
# todoist-python - The official Todoist Python API library
## How to get started

%package license
Summary: license components for the todoist package.
Group: Default

%description license
license components for the todoist package.


%package python
Summary: python components for the todoist package.
Group: Default
Requires: todoist-python3 = %{version}-%{release}

%description python
python components for the todoist package.


%package python3
Summary: python3 components for the todoist package.
Group: Default
Requires: python3-core

%description python3
python3 components for the todoist package.


%prep
%setup -q -n todoist-python-7.0.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555344502
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/todoist
cp LICENSE %{buildroot}/usr/share/package-licenses/todoist/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/todoist/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
